### ISSUE TITLE
Error messages output when building website

### ISSUE THREAD

**Issue by mpaglia0** [getpelican/pelican#3401]
- [ x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: 
- **Python version**: 3.11
- **Pelican version**: 4.10
- **Link to theme**: https://github.com/mpaglia0/Iudas
- **Links to plugins**: 
- **Link to your site**: https://www.mauriziopaglia.it/
- **Link to your source**: 
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: 

## Issue

  After update Pelican to 4.10 I receive following errors launching website build

Exception ignored in: <function WeakMethod.__new__.<locals>._cb at 0x7f81ee60e3e0>
Traceback (most recent call last):
  File "/usr/lib64/python3.11/weakref.py", line 57, in _cb
AttributeError: 'NoneType' object has no attribute '_alive'
Exception ignored in: <function WeakMethod.__new__.<locals>._cb at 0x7f81ee60e840>
Traceback (most recent call last):
  File "/usr/lib64/python3.11/weakref.py", line 57, in _cb
AttributeError: 'NoneType' object has no attribute '_alive'
Exception ignored in: <function WeakMethod.__new__.<locals>._cb at 0x7f81ee60eca0>
Traceback (most recent call last):
  File "/usr/lib64/python3.11/weakref.py", line 57, in _cb
AttributeError: 'NoneType' object has no attribute '_alive'

Errors are printed on the terminal after website has been built

Problem is still here after update to 4.10.1

Thanks

**Comment by justinmayer** [comment]
Hi Maurizio. I do not get the impression you have followed the steps in the [How to Get Help documentation](https://docs.getpelican.com/en/latest/contribute.html#how-to-get-help). That is, can you reproduce the error using a stock settings file, default theme, and the sample content? If not, then the problem is unlikely to be related to Pelican itself.

**Comment by mpaglia0** [comment]
Ciao Justin, I am sorry I will try

**Comment by justinmayer** [comment]
Too more thoughts…

1. If, after following the aforementioned steps, you can reproduce the problem reliably, please re-open this issue.
2. In the future, questions related to Pelican (including problems that cannot be reproduced using a stock settings file, default theme, and the sample content) are better suited as new topics within [Pelican Discussions](https://github.com/getpelican/pelican/discussions) (instead of being submitted as actionable issues here).

**Comment by projectgus** [comment]
For anyone else who stumbles across this, the root cause seems to be in the "blinker" dependency of the sitemap plugin. See https://github.com/pelican-plugins/sitemap/issues/35 and the blinker issue linked from there.

**Comment by justinmayer** [comment]
Nice work, Angus. As far as I recall, Blinker is a *Pelican* dependency — the Sitemap plugin has no direct dependencies other than Pelican itself. If the problem is not addressed upstream in a patched Blinker release sometime soon, we could consider pinning Blinker to 1.7 and releasing Pelican 4.10.2 as an interim workaround.

**Comment by justinmayer** [comment]
[Blinker 1.9.0](https://github.com/pallets-eco/blinker/releases/tag/1.9.0) has been released and contains a fix for this issue, thanks to @projectgus!
